# 血液样本分层检测的双模态YOLO配置

# 基本路径
project_dir: /Users/xin99/Documents/BloodScan
data_dir: /Users/xin99/Documents/BloodScan/data
weights_dir: /Users/xin99/Documents/BloodScan/dual_modal_yolo/weights
results_dir: /Users/xin99/Documents/BloodScan/dual_modal_yolo/results

# 数据集配置
train_white_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/train/white
train_blue_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/train/blue
train_annotation_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/train/labels

val_white_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/val/white
val_blue_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/val/blue
val_annotation_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/val/labels

test_white_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/test/white
test_blue_dir: /Users/xin99/Documents/BloodScan/data/blood_samples/test/blue

# 数据处理配置
img_size: 640
batch_size: 8
num_workers: 4
augment: true
prefix_white: ''
prefix_blue: ''
suffix_white: ''
suffix_blue: ''
pair_mode: filename

# 模型配置
model_cfg: yolov8s-seg.pt
white_weights: ''
blue_weights: ''
fusion_type: transformer
num_heads: 8
num_classes: 3

# 训练配置
epochs: 50
lr: 0.001
weight_decay: 0.0005
momentum: 0.937
freeze_backbone: true
amp: true
device: cuda

# 优化器配置
optimizer: Adam
lr_scheduler: cosine
warmup_epochs: 3

# 损失函数权重
box_loss_weight: 0.05
cls_loss_weight: 0.5
obj_loss_weight: 1.0
seg_loss_weight: 0.3

# 推理配置
conf_thres: 0.25
iou_thres: 0.45
max_det: 300 